name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.2); leave empty to use tag name without v'
        required: false

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        id: vars
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $inputVersion = "${{ github.event.inputs.version }}"
          if ([string]::IsNullOrWhiteSpace($inputVersion)) {
            if ($tag -like 'v*') { $ver = $tag.Substring(1) } else { $ver = $tag }
          } else { $ver = $inputVersion }
          echo "version=$ver" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Build installer
        shell: pwsh
        run: |
          scripts/build_installer.ps1 -Configuration Release -Rid win-x64 -Version "${{ steps.vars.outputs.version }}"

      - name: Build portable zip
        shell: pwsh
        run: |
          scripts/build_portable.ps1 -Configuration Release -Rid win-x64 -Version "${{ steps.vars.outputs.version }}"

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ChildGuard ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
          files: |
            dist/ChildGuardSetup_*.exe
            dist/ChildGuard_Portable_*.zip

